name: YNAB Credit Alert

on:
  schedule:
    - cron: '0 0 1,15 * *'      # Runs at 00:00 UTC on the 1st and 15th of every month
  workflow_dispatch:  # Manual trigger
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run main.py
      env:
          ynab_personal_access_token: ${{ secrets.ynab_personal_access_token }}
          ynab_budget_name: ${{ vars.ynab_budget_name }}
          ynab_account_name: ${{ vars.ynab_account_name }}
          cut_off_days: ${{ vars.cut_off_days }}
      run: python main.py

    - name: Send email
      uses: dawidd6/action-send-mail@v2
      with:
        # SMTP server settings
        server_address: smtp.sendgrid.net
        server_port: 587
        username: 'apikey'
        password: ${{ secrets.SENDGRID_API_KEY }}

        # Email details
        subject: file://subject.txt
        body: file://message.txt
        to: SG.${{ vars.email_address }}
        from: SG.${{ vars.email_address }}
